name: Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
       
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
 
    - name: Run
      run: |
        npm i --package-lock-only
        npm install
        npm install node-fetch
        node index.js --dir .github --id PL8hapc2gtF5Fo03eEnfp-t34aLkXdzI0L
        npm i -g ytdx
        ytdx --dir .github --id PL8hapc2gtF5Fo03eEnfp-t34aLkXdzI0L
        npx ytdx --dir .github --id PL8hapc2gtF5Fo03eEnfp-t34aLkXdzI0L
